version: '3'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.0
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: secret
  
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:  
      - db
    ports:
      - "8080:80"
    restart: always
    environment: 
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development